all:
	g++ -std=c++11 -o test SystemUsageWidget.cpp unitTest.cpp 
	g++ -std=c++11 -o sys SystemUsageWidget.cpp main.cpp

rsys:
	g++ -std=c++11 -o sys SystemUsageWidget.cpp main.cpp
	./sys

rtest:
	g++ -std=c++11 -o test SystemUsageWidget.cpp unitTest.cpp 
	./test

