all:
	g++ -std=c++11 -o test memorycard.cpp unittests.cpp
	g++ -std=c++11 -o game memorycard.cpp main.cpp

rgame:
	g++ -std=c++11 -o game memorycard.cpp main.cpp
	./game

rtest:
	g++ -std=c++11 -o test memorycard.cpp unittests.cpp
	./test

