all:
	g++ -std=c++11 -o test TicTacToe.cpp unitTest.cpp 
	g++ -std=c++11 -o game TicTacToe.cpp main.cpp

rgame:
	g++ -std=c++11 -o game TicTacToe.cpp main.cpp
	./game

rtest:
	g++ -std=c++11 -o test TicTacToe.cpp unitTest.cpp 
	./test

