all:
	g++ -std=c++11 -o test mathgame.cpp unitTest.cpp 
	g++ -std=c++11 -o game mathgame.cpp main.cpp

rgame:
	g++ -std=c++11 -o game mathgame.cpp main.cpp
	./game

rtest:
	g++ -std=c++11 -o test mathgame.cpp unitTest.cpp 
	./test

